plugins {
    id "fabric-loom" version "1.6-SNAPSHOT"
    id "maven-publish"
}

version = project.mod_version
group = project.maven_group

repositories {
    mavenCentral()
    maven { url "https://maven.fabricmc.net/" }
}

dependencies {
    minecraft "com.mojang:minecraft:1.21"
    mappings "net.fabricmc:yarn:1.21+build.9:v2"

    modImplementation "net.fabricmc:fabric-loader:0.16.0"
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.100.8+1.21"
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

loom {
    splitEnvironmentSourceSets()
mixin {
        defaultRefmapName = "minecraftdebugging-refmap.json"
    }
}
